/*

    LLVMConstAShr⚠
    LLVMConstAdd⚠
    LLVMConstAddrSpaceCast⚠
    LLVMConstAllOnes⚠
    LLVMConstAnd⚠
    LLVMConstArray⚠
    LLVMConstBitCast⚠
    LLVMConstExactSDiv⚠
    LLVMConstExactUDiv⚠
    LLVMConstExtractElement⚠
    LLVMConstExtractValue⚠
    LLVMConstFAdd⚠
    LLVMConstFCmp⚠
    LLVMConstFDiv⚠
    LLVMConstFMul⚠
    LLVMConstFNeg⚠
    LLVMConstFPCast⚠
    LLVMConstFPExt⚠
    LLVMConstFPToSI⚠
    LLVMConstFPToUI⚠
    LLVMConstFPTrunc⚠
    LLVMConstFRem⚠
    LLVMConstFSub⚠
    LLVMConstGEP⚠
    LLVMConstGEP2⚠
    LLVMConstICmp⚠
    LLVMConstInBoundsGEP⚠
    LLVMConstInBoundsGEP2⚠
    LLVMConstInlineAsm⚠Deprecated
    LLVMConstInsertElement⚠
    LLVMConstInsertValue⚠
    LLVMConstInt⚠
    LLVMConstIntCast⚠
    LLVMConstIntGetSExtValue⚠
    LLVMConstIntGetZExtValue⚠
    LLVMConstIntOfArbitraryPrecision⚠
    LLVMConstIntOfString⚠
    LLVMConstIntOfStringAndSize⚠
    LLVMConstIntToPtr⚠
    LLVMConstLShr⚠
    LLVMConstMul⚠
    LLVMConstNSWAdd⚠
    LLVMConstNSWMul⚠
    LLVMConstNSWNeg⚠
    LLVMConstNSWSub⚠
    LLVMConstNUWAdd⚠
    LLVMConstNUWMul⚠
    LLVMConstNUWNeg⚠
    LLVMConstNUWSub⚠
    LLVMConstNamedStruct⚠
    LLVMConstNeg⚠
    LLVMConstNot⚠
    LLVMConstNull⚠
    LLVMConstOr⚠
    LLVMConstPointerCast⚠
    LLVMConstPointerNull⚠
    LLVMConstPtrToInt⚠
    LLVMConstReal⚠
    LLVMConstRealGetDouble⚠
    LLVMConstRealOfString⚠
    LLVMConstRealOfStringAndSize⚠
    LLVMConstSDiv⚠
    LLVMConstSExt⚠
    LLVMConstSExtOrBitCast⚠
    LLVMConstSIToFP⚠
    LLVMConstSRem⚠
    LLVMConstSelect⚠
    LLVMConstShl⚠
    LLVMConstShuffleVector⚠
    LLVMConstString⚠
    LLVMConstStringInContext⚠
    LLVMConstStruct⚠
    LLVMConstStructInContext⚠
    LLVMConstSub⚠
    LLVMConstTrunc⚠
    LLVMConstTruncOrBitCast⚠
    LLVMConstUDiv⚠
    LLVMConstUIToFP⚠
    LLVMConstURem⚠
    LLVMConstVector⚠
    LLVMConstXor⚠
    LLVMConstZExt⚠
    LLVMConstZExtOrBitCast⚠

*/
