/*
    LLVMCreateMemoryBufferWithContentsOfFile⚠
    LLVMCreateMemoryBufferWithMemoryRange⚠
    LLVMCreateMemoryBufferWithMemoryRangeCopy⚠
    LLVMCreateMemoryBufferWithSTDIN⚠
    LLVMDisposeMemoryBuffer⚠
    LLVMGetBufferSize⚠
    LLVMGetBufferStart⚠
*/
